server {
    listen 127.0.0.1:8081;
    server_name default_server;
    client_max_body_size 1M;

    error_page 404 404.html;

    location / {
        root /www;
        index index.html;
        methods GET;
        autoindex on;
    }
}