Token(WORD, value="user", line=1, column=1)
Token(WORD, value="nginx", line=1, column=7)
Token(SEMICOLON, value=";", line=1, column=12)
Token(WORD, value="worker_processes", line=2, column=1)
Token(WORD, value="auto", line=2, column=19)
Token(SEMICOLON, value=";", line=2, column=23)
Token(WORD, value="error_log", line=3, column=1)
Token(WORD, value="/var/log/nginx/error.log", line=3, column=12)
Token(WORD, value="notice", line=3, column=37)
Token(SEMICOLON, value=";", line=3, column=43)
Token(WORD, value="pid", line=4, column=1)
Token(WORD, value="/run/nginx.pid", line=4, column=12)
Token(SEMICOLON, value=";", line=4, column=26)
Token(WORD, value="events", line=6, column=1)
Token(LBRACE, value="{", line=6, column=8)
Token(WORD, value="worker_connections", line=7, column=5)
Token(NUMBER, value="1024", line=7, column=25)
Token(SEMICOLON, value=";", line=7, column=29)
Token(RBRACE, value="}", line=8, column=1)
Token(WORD, value="http", line=10, column=1)
Token(LBRACE, value="{", line=10, column=6)
Token(WORD, value="include", line=11, column=5)
Token(WORD, value="/etc/nginx/mime.types", line=11, column=19)
Token(SEMICOLON, value=";", line=11, column=40)
Token(WORD, value="default_type", line=12, column=5)
Token(WORD, value="application/octet-stream", line=12, column=19)
Token(SEMICOLON, value=";", line=12, column=43)
Token(WORD, value="log_format", line=13, column=5)
Token(WORD, value="main", line=13, column=17)
Token(WORD, value="'$remote_addr", line=13, column=23)
Token(WORD, value="-", line=13, column=37)
Token(WORD, value="$remote_user", line=13, column=39)
Token(WORD, value="[$time_local]", line=13, column=52)
Token(WORD, value=""$request"", line=13, column=66)
Token(WORD, value="'", line=13, column=77)
Token(WORD, value="'$status", line=14, column=23)
Token(WORD, value="$body_bytes_sent", line=14, column=32)
Token(WORD, value=""$http_referer"", line=14, column=49)
Token(WORD, value="'", line=14, column=65)
Token(WORD, value="'"$http_user_agent"", line=15, column=23)
Token(WORD, value=""$http_x_forwarded_for"'", line=15, column=43)
Token(SEMICOLON, value=";", line=15, column=67)
Token(WORD, value="access_log", line=16, column=5)
Token(WORD, value="/var/log/nginx/access.log", line=16, column=17)
Token(WORD, value="main", line=16, column=44)
Token(SEMICOLON, value=";", line=16, column=48)
Token(WORD, value="sendfile", line=17, column=5)
Token(WORD, value="on", line=17, column=21)
Token(SEMICOLON, value=";", line=17, column=23)
Token(WORD, value="keepalive_timeout", line=19, column=5)
Token(NUMBER, value="65", line=19, column=24)
Token(SEMICOLON, value=";", line=19, column=26)
Token(WORD, value="include", line=21, column=5)
Token(WORD, value="/etc/nginx/conf.d/*.conf", line=21, column=13)
Token(SEMICOLON, value=";", line=21, column=37)
Token(RBRACE, value="}", line=22, column=1)
Token(END_OF_FILE, value="", line=22, column=2)
