worker_processes auto;

http {
	server {
		listen 8080;
		server_name site1.com site2.com site3.com site4.com site5.com site6.com site7.com site8.com site9.com site10.com site11.com site12.com site13.com site14.com site15.com site16.com site17.com site18.com site19.com site20.com;
		root /var/www/html;
	}
}
