worker_processes 2;

http {
	server {
		listen 8080;
		server_name example.com;
		root /var/www/html;

		location / {
			index index.html;
			autoindex on;
		}

		location /api {
			root /var/www/api;
			return 200;
		}
	}
}
