# Invalid: two location blocks with the same path '/'.
server {
    listen 127.0.0.1:8085;
    client_max_body_size 2m;
    root /www/;

    location / {
        index index.html;
        methods GET;
    }

    location / {
        index index.html;
        methods POST;
    }
}
