# Invalid: 'root' declared twice in the same server block.
server {
    listen 127.0.0.1:8085;
    client_max_body_size 2m;
    root /www/;
    root /www/;

    location / {
        index index.html;
        methods GET;
    }
}
