# Invalid: 'index' declared twice in the same location block.
server {
    listen 127.0.0.1:8085;
    client_max_body_size 2m;
    root /www/;

    location / {
        index index.html;
        index index.html;
        methods GET;
    }
}
