# Invalid: 'server_name' declared twice in the same server block.
server {
    listen 127.0.0.1:8085;
    client_max_body_size 2m;
    server_name "Server A";
    server_name "Server B";
    root /www/;

    location / {
        index index.html;
        methods GET;
    }
}
