server {
    listen 127.0.0.1:8080;
    listen 127.0.0.1:8082;
    server_name "Server 1";
    client_max_body_size 2m;
    keepalive_timeout 2;

    error_page 404 404.html;
    error_page 500 502 503 =200 50x.html;

    root /www/;

    autoindex on;

    cgi_handler .py /usr/bin/python3;

    location / {
        index index.html;
        root /tester/;
        methods GET POST;
        autoindex off;
    }

    location /uploads {
        methods GET;
    }

    location /cgi-bin {
        index script.py;
    }
}


server {
    listen 0.0.0.0:8081;
    server_name server2;
    client_max_body_size 1M;

    error_page 404 404.html;

    location / {
        root /www/;
        index index.html;
        methods GET;
        autoindex on;
    }

    # location /redirect {
    #     return 301 https://newdomain.com;
    # }
}

# server {
#     listen 127.0.0.1:8083;
#     server_name server3;
#     client_max_body_size 2M;

#     error_page 404 /error_pages/not_found.html;
#     error_page 500 /error_pages/server_error.html;

#     location / {
#         root /www/cgi-bin;
#         index index.html;
#         methods GET POST;
#     }

#     location /cgi-bin {
#         root /www/cgi-bin;
#         methods GET POST;
#         cgi_extension .py;
#         cgi_path /usr/bin/python3;
#     }
# }