server {
    listen localhost:8080;
    server_name "Server 1";
    client_max_body_size 2m;
    keepalive_timeout 2;

    error_page 404 404.html;
    error_page 500 502 503 50x.html;

    location / {
        root /www/;
        index index.html;
        methods GET POST;
        autoindex off;
    }

    location /upload {
        root /www/uploads;
        methods POST;
    }
}

# server {
#     listen localhost:8080;
#     server_name server2;
#     client_max_body_size 1M;

#     error_page 404 error_pages/404.html;

#     location / {
#         root /www/static;
#         index index.html;
#         methods GET;
#         autoindex on;
#     }

#     location /images {
#         root /www/static/images;
#         methods GET;
#         autoindex on;
#     }

#     location /redirect {
#         return 301 https://newdomain.com;
#     }
# }

# server {
#     listen 127.0.0.1:8083;
#     server_name server3;
#     client_max_body_size 2M;

#     error_page 404 /error_pages/not_found.html;
#     error_page 500 /error_pages/server_error.html;

#     location / {
#         root /www/cgi-bin;
#         index index.html;
#         methods GET POST;
#     }

#     location /cgi-bin {
#         root /www/cgi-bin;
#         methods GET POST;
#         cgi_extension .py;
#         cgi_path /usr/bin/python3;
#     }
# }