worker_processes 1;

http {
	allow 10.0.0.1;
	deny 192.168.1.0/24;

	server {
		listen 8080;
		server_name example.com;
		root /var/www/html;

		allow all;

		location / {
			index index.html;
			deny 172.16.0.0/16;
		}
	}
}
