worker_processes auto;

http {
	server {
		listen 8080;
		server_name api.example.com;
		root /var/www/api;

		location /admin {
			root /var/www/admin;

			limit_except GET POST {
				allow 192.168.1.0/24;
				deny all;
			}
		}
	}
}
